sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "10.8.0"

branches:
  only:
    - master

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - npm install -g @angular/cli

script:
  - npm run build.prod
# just to test
# before_deploy:
#   - npm run ghp.fix.paths

# deploy:
#     provider: pages
#     skip_cleanup: true # Prevent travis from cleaning out the branch before the deploy occurs
#     github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#     local-dir: dist/tryNgrxStore
#     on:
#         branch: master # Build only from master
